{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gpgr
  version: {{ GIT_DESCRIBE_TAG }}

source:

  git_url: https://github.com/umccr/gpgr
  git_tag: master

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-assertthat
    - r-bedr
    - bioconductor-bsgenome.hsapiens.ucsc.hg38
    - r-chord
    - r-dplyr
    - r-ggplot2
    - r-glue
    - r-gtools
    - r-jsonlite
    - r-purrr
    - r-readr
    - r-rlang
    - r-scales
    - r-signature.tools.lib
    - r-stringr
    - bioconductor-structuralvariantannotation
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - bioconductor-variantannotation

  run:
    - r-base
    - r-assertthat
    - r-bedr
    - bioconductor-bsgenome.hsapiens.ucsc.hg38
    - r-chord
    - r-dplyr
    - r-ggplot2
    - r-glue
    - r-gtools
    - r-jsonlite
    - r-purrr
    - r-readr
    - r-rlang
    - r-scales
    - r-signature.tools.lib
    - r-stringr
    - bioconductor-structuralvariantannotation
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - bioconductor-variantannotation

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('gpgr')"           # [not win]
    - "\"%R%\" -e \"library('gpgr')\""  # [win]

about:
  home: https://github.com/umccr/gpgr
  license: MIT + file LICENSE
  summary: Genomics Platform Group Reporting
  license_family: MIT

