name: conda-pkgdown

on: [push]

jobs:
  build-conda-deploy-pkgdown:
    name: Build conda package and deploy pkgdown website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v1
        with:
          # Do everything inside the base env
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
          mamba-version: "*"
          conda-build-version: "3.20"
          channels: "pdiakumis,conda-forge,bioconda"

      - name: Build conda package
        shell: bash -l {0}
        run: mamba build --R 4.0 conda/gpgr

      - name: Install conda packages
        shell: bash -l {0}
        run: mamba create -n pkgdown_gpgr --use-local r-gpgr r-pkgdown pandoc

      - name: Test
        shell: bash -l {0}
        run: |
            conda activate pkgdown_gpgr
            Rscript -e "capabilities()"
            Rscript -e "packageVersion('gpgr')"
            Rscript -e "packageVersion('pkgdown')"
            Rscript -e "install.packages('Cairo', repos = c(CRAN = 'https://cran.ms.unimelb.edu.au'))"
            Rscript -e "packageVersion('Cairo')"

      - name: Conda list
        shell: bash -l {0}
        run: conda list -n pkgdown_gpgr
